### ISSUE TITLE
Sometimes counts past a number

### ISSUE THREAD

**Issue by taitems** [saadeghi/svelte-countup#2]
I've noticed sometimes (not always) that the plugin appears to count past the target number and snap back, like an elastic overshoot easing equation. Is this deliberate? Is this a rounding/decimal error? Is it due to the easing equation?

Thanks for your plugin, of course.

**Comment by saadeghi** [comment]
Is it the same value, but the issue happens sometimes?  
How can I reproduce? 🤔

**Comment by taitems** [comment]
Hello, managed to reproduce in a Svelte repl.

Here's the raw code. You'll hopefully see it counting up to 13 and then back to 12.

```svelte
<script>
   import Countup from 'svelte-countup';
</script>

<Countup
   initial={10}
   value={12}
   duration={500}
   format={false}
/>
```

**Comment by saadeghi** [comment]
I see. Thanks!

**Comment by sbscan** [comment]
Indeed it always make it lite this but when start value and new value difference is big we can't see it.
Quick solution is if difference is small, make duration small or even 1.
I'll check the code and try to figure out when I have time, maybe I can help.

**Comment by joefhall** [comment]
Hello, I'm getting the same issue with this code -- it counts up to 7 then goes back down to 6:

`<Countup value={6} />`

Is it a bug with small numbers?

I tried reducing the `duration` but it's still a noticeable problem.

Thanks for looking into this

**Comment by saadeghi** [comment]
Fixed in latest version!

**Comment by joefhall** [comment]
Great, thank you!
